### ISSUE TITLE
Install CRDs with Helm 3 instead of using installCrd=true value

### ISSUE THREAD

**Issue by robinmanuelthiel** [SparebankenVest/public-helm-charts#18] opened 2020-03-03 14:25 UTC
With the arrival of Helm 3, [Helm can now take care of installing CRDs](https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource) for us. This would make the installation a lot easier, as we could get rid of the `--set installCrd=true` value, the first time we install the chart.

It would also make it easier to integrate the Helm Charts into CD pipelines, as the pipeline doesn't have to know anymore if it runs against a cluster for the first or hundredth time.

**Comment by torresdal** [comment] 2020-03-03 16:05
Agree @robinmanuelthiel . Actually started the work here: https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/akv2k8s

I’ve also merged the two charts into one. 

Think we need to support both versions for some time though. Recently I merged a few pull request with improvements to the old charts, but these are not in the new chart. 

Take a look and let us know. Should not be too much work to get it live.

**Comment by agniveshadhikari** [comment] 2020-08-24 14:59
@torresdal First of all, a huge thank you for maintaining this project. It has been a lifesaver!

About this issue, the chart `spv/azure-key-vault-controller` still uses the Helm2 way of CRDs in templates. I saw that you started working on it. Just wanted to ask why you haven't updated the dependency yet. Is there a blocker that's stopping the final integration?

I am using `akv2k8s` project, and because of this behavior, I can't also create a `AzureKeyVaultSecret` resource in the same chart that installs `akv2k8s`, due to a race condition. I believe adding the CRD the Helm3 way would solve this.

**Comment by torresdal** [comment] 2020-09-20 22:01
This took some time, but I believe the akv2k8s chart is ready for public consumption. I've added a deprecation warning to the other charts and will keep the akv2k8s chart updated going forward.

Regarding crds, even with Helm 3 it's not unproblematic, at least not from our point of view (ref: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) - and we've decided to keep the crd's outside of the helm chart and must be installed/updated manually. This seams to be the norm in other projects as well. If you have a different opinion I would gladly hear your view. 

@agniveshadhikari would handling the crd outside the chart be problematic for your usage of akv2k8s?

**Comment by robinmanuelthiel** [comment] 2020-09-23 12:32
Well, that's unfortunate. In my case, I use Terraform, to get the cluster in a state, where developers can deploy their applications. Part of that Terraform script is to not only create the Kubernetes cluster itself but also install a bunch of cluster-wide helm charts. One of them is akv2k8s.

The problem: Terraform can't install CRDs or any custom YAML files at the moment through the Kubernetes provider. So I was using the Helm provider to install the Helm chart and the CRDs with them. Now, that I don't have the option of installing the CRDs through helm anymore, I need a bunch of custom scripting.

Beside akv2k8s, I also install *AAD Pod Identity* and *Cert Manager*. Both can install their CRDs through Helm btw...

**Comment by torresdal** [comment] 2020-09-23 12:37
@robinmanuelthiel yea - think I jumped the gun on this one. I was actually planning on putting the crd back again, just need to find the time... so very soon.

**Comment by torresdal** [comment] 2020-09-25 23:15
@robinmanuelthiel crds are back

**Comment by robinmanuelthiel** [comment] 2020-10-15 09:26
Hi @torresdal, installing the CRDs via Helm does not seem to work with the latest version.

Before installing the Helm chart, I deleted all previously installed CRDs. When firing the following command:

```bash
helm upgrade -i akv2k8s spv-charts/akv2k8s \
    --namespace akv2k8s \
    --set env_injector.enabled=false \
    --set controller.customAuth.enabled=true \
    --set controller.podLabels.aadpodidbinding=mypodidentity
```

the following error occurs

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "azurekeyvaultsecrets.spv.no" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "akv2k8s"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "akv2k8s"
```

**Comment by torresdal** [comment] 2020-10-18 07:04
@robinmanuelthiel this was caused by old crd template resources that was left behind. Sorry for this. These are now removed in chart version `1.1.25`.

Note: You probably know this already, but keep in mind that when you delete the CRD, all AzureKeyVaultSecret resources will also be deleted.

**Closed** 2020-10-27 04:27 UTC
